version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      production:
        dependency-type: production
      development:
        dependency-type: development
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /ui
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      ui-deps:
        patterns:
          - "*"
    labels:
      - dependencies
      - ui

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - ci
