import { Summary } from '../types/summary.js';

/**
 * Summary Templates - Generate formatted output from task summaries
 *
 * Supports:
 * - PR descriptions (GitHub, GitLab, Bitbucket)
 * - Changelog entries (Keep a Changelog format)
 * - Release notes
 * - Commit messages (Conventional Commits)
 */

/**
 * Task type templates with conventional commit prefixes and changelog categories
 */
export const TASK_TYPE_TEMPLATES: Record<string, {
  title: string;
  prPrefix: string;
  changelogCategory: 'Added' | 'Changed' | 'Fixed' | 'Removed' | 'Security' | 'Deprecated';
  emoji: string;
}> = {
  feature: { title: 'New Feature', prPrefix: 'feat', changelogCategory: 'Added', emoji: '✨' },
  bug_fix: { title: 'Bug Fix', prPrefix: 'fix', changelogCategory: 'Fixed', emoji: '🐛' },
  refactor: { title: 'Refactoring', prPrefix: 'refactor', changelogCategory: 'Changed', emoji: '♻️' },
  documentation: { title: 'Documentation', prPrefix: 'docs', changelogCategory: 'Changed', emoji: '📚' },
  performance: { title: 'Performance', prPrefix: 'perf', changelogCategory: 'Changed', emoji: '⚡' },
  security: { title: 'Security', prPrefix: 'security', changelogCategory: 'Security', emoji: '🔒' },
  test: { title: 'Testing', prPrefix: 'test', changelogCategory: 'Changed', emoji: '🧪' },
  chore: { title: 'Maintenance', prPrefix: 'chore', changelogCategory: 'Changed', emoji: '🔧' },
  deprecation: { title: 'Deprecation', prPrefix: 'deprecate', changelogCategory: 'Deprecated', emoji: '⚠️' },
  removal: { title: 'Removal', prPrefix: 'remove', changelogCategory: 'Removed', emoji: '🗑️' },
};

/**
 * PR description format options
 */
export interface PRDescriptionOptions {
  format?: 'github' | 'gitlab' | 'bitbucket' | 'simple';
  includeFileChanges?: boolean;
  includeDecisions?: boolean;
  includeBlockers?: boolean;
  includeTokenStats?: boolean;
}

/**
 * Generate a GitHub-formatted Pull Request description from a summary
 */
export function generatePRDescription(summary: Summary, options: PRDescriptionOptions = {}): string {
  const {
    includeFileChanges = true,
    includeDecisions = true,
    includeBlockers = true,
    includeTokenStats = false,
  } = options;

  const taskType = summary.taskType || 'feature';
  const template = TASK_TYPE_TEMPLATES[taskType] || TASK_TYPE_TEMPLATES.feature;

  let body = `## ${template.emoji} Summary\n\n`;
  body += `${summary.whatChanged}\n\n`;

  if (summary.whyChanged) {
    body += `### 💡 Why\n${summary.whyChanged}\n\n`;
  }

  if (summary.howChanged) {
    body += `### 🔧 How\n${summary.howChanged}\n\n`;
  }

  if (includeFileChanges && summary.filesChanged && summary.filesChanged.length > 0) {
    body += `### 📁 Files Changed\n`;
    summary.filesChanged.forEach(f => {
      const file = f as { path?: string; action?: string; additions?: number; deletions?: number };
      if (typeof f === 'string') {
        body += `- \`${f}\`\n`;
      } else if (file.path) {
        const icon = file.action === 'created' ? '🆕' : file.action === 'deleted' ? '🗑️' : '📝';
        const stats = (file.additions !== undefined || file.deletions !== undefined)
          ? ` [+${file.additions || 0}/-${file.deletions || 0}]`
          : '';
        body += `- ${icon} \`${file.path}\`${stats}\n`;
      }
    });
    body += '\n';
  }

  if (includeDecisions && summary.decisions && summary.decisions.length > 0) {
    body += `### 🎯 Key Decisions\n`;
    summary.decisions.forEach(d => {
      const decision = d as { description?: string; reason?: string };
      if (typeof d === 'string') {
        body += `- ${d}\n`;
      } else if (decision.description) {
        body += `- **${decision.description}**${decision.reason ? `: ${decision.reason}` : ''}\n`;
      }
    });
    body += '\n';
  }

  if (includeBlockers && summary.blockers && summary.blockers.length > 0) {
    body += `### ⚠️ Known Issues\n`;
    summary.blockers.forEach(b => {
      const blocker = b as { description?: string; severity?: string };
      if (typeof b === 'string') {
        body += `- ${b}\n`;
      } else if (blocker.description) {
        const severityIcon = blocker.severity === 'critical' ? '🔴' : blocker.severity === 'error' ? '🟠' : '🟡';
        body += `- ${severityIcon} ${blocker.description}\n`;
      }
    });
    body += '\n';
  }

  if (includeTokenStats && summary.tokensUsed) {
    const tokens = summary.tokensUsed as { total?: number };
    body += `### 📊 AI Stats\n`;
    body += `- Tokens: ${tokens.total?.toLocaleString() || 'N/A'}\n`;
    if (summary.cost) {
      const cost = summary.cost as { amount?: number };
      body += `- Cost: $${cost.amount?.toFixed(4) || '0.0000'}\n`;
    }
    body += '\n';
  }

  body += `---\n*Generated by [GLINR](https://github.com/GLINCKER/glinr-task-manager) • Agent: ${summary.agent}*`;

  return body;
}

/**
 * Changelog options
 */
export interface ChangelogOptions {
  version?: string;
  date?: string;
  format?: 'keepachangelog' | 'simple' | 'grouped';
  includeIssueLinks?: boolean;
  issueLinkBase?: string;
}

/**
 * Generate a release changelog from a collection of summaries
 * Uses Keep a Changelog format by default
 */
export function generateChangelog(summaries: Summary[], options: ChangelogOptions | string = {}): string {
  // Support old API: generateChangelog(summaries, version)
  const opts: ChangelogOptions = typeof options === 'string' ? { version: options } : options;
  const {
    version = 'Unreleased',
    date = new Date().toISOString().split('T')[0],
    format = 'keepachangelog',
    includeIssueLinks = true,
    issueLinkBase = '',
  } = opts;

  if (format === 'simple') {
    // Simple grouped format (original behavior)
    let changelog = `# Changelog - ${version} (${date})\n\n`;
    const groups: Record<string, Summary[]> = {};

    summaries.forEach(s => {
      const groupKey = s.taskType || s.agent || 'Other';
      if (!groups[groupKey]) groups[groupKey] = [];
      groups[groupKey].push(s);
    });

    for (const [groupName, groupSummaries] of Object.entries(groups)) {
      const formattedGroup = groupName.charAt(0).toUpperCase() + groupName.slice(1);
      changelog += `## ${formattedGroup}\n`;

      groupSummaries.forEach(s => {
        changelog += `- **${s.title}**: ${s.whatChanged.split('\n')[0]}\n`;
        if (includeIssueLinks && s.linkedIssue) {
          changelog += `  - Linked Issue: #${s.linkedIssue}\n`;
        }
      });

      changelog += '\n';
    }

    return changelog;
  }

  // Keep a Changelog format (default)
  const grouped: Record<string, Summary[]> = {
    Added: [],
    Changed: [],
    Fixed: [],
    Removed: [],
    Security: [],
    Deprecated: [],
  };

  for (const summary of summaries) {
    const taskType = summary.taskType || 'feature';
    const template = TASK_TYPE_TEMPLATES[taskType] || TASK_TYPE_TEMPLATES.feature;
    grouped[template.changelogCategory].push(summary);
  }

  let changelog = `## [${version}] - ${date}\n\n`;

  for (const [category, items] of Object.entries(grouped)) {
    if (items.length === 0) continue;

    changelog += `### ${category}\n\n`;

    for (const summary of items) {
      let entry = `- ${summary.whatChanged.split('\n')[0]}`;
      if (includeIssueLinks && summary.linkedIssue) {
        const issueNum = summary.linkedIssue.replace(/[^\d]/g, '');
        entry += issueLinkBase
          ? ` ([#${issueNum}](${issueLinkBase}${issueNum}))`
          : ` (#${issueNum})`;
      }
      changelog += `${entry}\n`;
    }

    changelog += '\n';
  }

  return changelog;
}

/**
 * Generate release notes from summaries
 */
export function generateReleaseNotes(
  summaries: Summary[],
  options: { version: string; title?: string; includeStats?: boolean } = { version: '1.0.0' }
): string {
  const { version, title = `Release ${version}`, includeStats = true } = options;

  let notes = `# ${title}\n\n`;

  if (includeStats) {
    const stats = { features: 0, fixes: 0, other: 0, totalFiles: 0 };
    for (const summary of summaries) {
      const taskType = summary.taskType || 'feature';
      if (taskType === 'feature') stats.features++;
      else if (taskType === 'bug_fix') stats.fixes++;
      else stats.other++;
      stats.totalFiles += (summary.filesChanged || []).length;
    }

    notes += `## 📊 Overview\n\n`;
    notes += `- **${stats.features}** new features\n`;
    notes += `- **${stats.fixes}** bug fixes\n`;
    if (stats.other > 0) notes += `- **${stats.other}** other improvements\n`;
    notes += `- **${stats.totalFiles}** files modified\n\n`;
  }

  // Features
  const features = summaries.filter(s => (s.taskType || 'feature') === 'feature');
  if (features.length > 0) {
    notes += `## ✨ Features\n\n`;
    for (const s of features) {
      notes += `- **${s.title}**: ${s.whatChanged.split('\n')[0]}\n`;
    }
    notes += '\n';
  }

  // Bug fixes
  const fixes = summaries.filter(s => s.taskType === 'bug_fix');
  if (fixes.length > 0) {
    notes += `## 🐛 Bug Fixes\n\n`;
    for (const s of fixes) {
      notes += `- **${s.title}**: ${s.whatChanged.split('\n')[0]}\n`;
    }
    notes += '\n';
  }

  // Other
  const other = summaries.filter(s => !['feature', 'bug_fix'].includes(s.taskType || 'feature'));
  if (other.length > 0) {
    notes += `## 🔧 Other Changes\n\n`;
    for (const s of other) {
      const template = TASK_TYPE_TEMPLATES[s.taskType || 'chore'] || TASK_TYPE_TEMPLATES.chore;
      notes += `- ${template.emoji} **${s.title}**: ${s.whatChanged.split('\n')[0]}\n`;
    }
    notes += '\n';
  }

  notes += `---\n*Generated by GLINR Task Manager*`;

  return notes;
}

/**
 * Get conventional commit prefix for a task type
 */
export function getConventionalCommitPrefix(taskType: string): string {
  const template = TASK_TYPE_TEMPLATES[taskType];
  return template?.prPrefix || 'chore';
}

/**
 * Generate a conventional commit message from a summary
 */
export function generateCommitMessage(
  summary: Summary,
  options: { maxLength?: number; includeBody?: boolean } = {}
): string {
  const { maxLength = 72, includeBody = false } = options;

  const taskType = summary.taskType || 'feature';
  const prefix = getConventionalCommitPrefix(taskType);
  const scope = summary.component ? `(${summary.component})` : '';

  let subject = `${prefix}${scope}: ${summary.title}`;
  if (subject.length > maxLength) {
    subject = subject.substring(0, maxLength - 3) + '...';
  }

  if (!includeBody) {
    return subject;
  }

  let message = `${subject}\n\n${summary.whatChanged}`;

  if (summary.linkedIssue) {
    message += `\n\nCloses ${summary.linkedIssue}`;
  }

  return message;
}
