import type { Task, TaskResult } from '../types/task.js';
import { GitHubClient } from '../integrations/github-client.js';
import { JiraClient } from '../integrations/jira-client.js';
import { LinearClient } from '../integrations/linear-client.js';
import { getTaskSummaries } from '../summaries/storage.js';
import { logger } from '../utils/logger.js';
import type { Summary } from '../types/summary.js';

/**
 * Post task result back to the source
 */
export async function postResultToSource(task: Task, result: TaskResult): Promise<void> {
  const summaries = await getTaskSummaries(task.id);
  const summary = summaries[0] || null;

  const body = buildNotificationBody(summary, result);

  if (task.source === 'github_issue' || task.source === 'github_pr') {
    await postGitHubComment(task, body);
  } else if (task.source === 'jira') {
    await postJiraComment(task, body);
  } else if (task.source === 'linear_issue' || task.source === 'linear_comment') {
    await postLinearComment(task, body);
  }
}

/**
 * Build a structured notification body from a summary or raw result
 */
function buildNotificationBody(summary: Summary | null, result: TaskResult): string {
  let body = '';
  
  if (summary) {
    // Build a rich comment from the structured summary
    body = `## 🤖 AI Transformation Complete: ${summary.title}\n\n`;
    body += `**Status:** ${result.success ? '✅ Success' : '❌ Failed'}\n\n`;
    
    body += `### 📝 What Changed\n${summary.whatChanged}\n\n`;
    
    if (summary.whyChanged) {
      body += `### 🎯 Rationale\n${summary.whyChanged}\n\n`;
    }

    if (summary.filesChanged && summary.filesChanged.length > 0) {
      body += `### 📂 Files Modified\n`;
      summary.filesChanged.forEach(f => {
        const icon = f.action === 'created' ? '🆕' : f.action === 'deleted' ? '🗑️' : '📝';
        body += `- ${icon} \`${f.path}\`\n`;
      });
      body += '\n';
    }

    if (summary.decisions && summary.decisions.length > 0) {
      body += `### 💡 Key Decisions\n`;
      summary.decisions.forEach(d => body += `- ${d.description}${d.reason ? ` (${d.reason})` : ''}\n`);
      body += '\n';
    }

    if (summary.artifacts && summary.artifacts.length > 0) {
      body += `### 📦 Artifacts\n`;
      summary.artifacts.forEach(a => {
        const link = a.url ? `([link](${a.url}))` : '';
        const label = (a as any).title || (a as any).identifier || (a as any).type;
        body += `- **${a.type}**: ${label} ${link}\n`;
      });
      body += '\n';
    }
  } else {
    // Fallback to raw output if no summary exists
    body = `## 🤖 AI Task Result\n\n`;
    body += `**Status:** ${result.success ? '✅ Completed' : '❌ Failed'}\n\n`;
    if (result.output) {
      body += `### Summary\n\n${result.output}\n\n`;
    }
  }

  if (result.error) {
    body += `### ⚠️ Error\n\`\`\`\n${result.error.message}\n\`\`\`\n\n`;
  }

  body += `---\n*Generated by [GLINR](https://github.com/GLINCKER/glinr-task-manager) • ${result.duration ? `Duration: ${(result.duration / 1000).toFixed(1)}s` : ''}*`;

  return body;
}

/**
 * Post a comment on GitHub
 */
async function postGitHubComment(task: Task, body: string): Promise<void> {
  const token = process.env.GITHUB_TOKEN;
  if (!token || !task.repository || !task.sourceId) return;

  try {
    const client = new GitHubClient(token);
    const issueNumber = parseInt(task.sourceId);
    await client.addComment(task.repository, issueNumber, body);
    logger.info(`[GitHub] Posted result to #${issueNumber} in ${task.repository}`);
  } catch (error) {
    logger.error('[GitHub] Error posting comment:', error as Error);
  }
}

/**
 * Post a comment on Jira
 */
async function postJiraComment(task: Task, body: string): Promise<void> {
  const baseUrl = process.env.JIRA_BASE_URL;
  const email = process.env.JIRA_EMAIL;
  const apiToken = process.env.JIRA_API_TOKEN;

  if (!baseUrl || !email || !apiToken || !task.sourceId) return;

  try {
    const client = new JiraClient({ baseUrl, email, apiToken });
    await client.addComment(task.sourceId, body);
    logger.info(`[Jira] Posted result to ${task.sourceId}`);
  } catch (error) {
    logger.error('[Jira] Error posting comment:', error as Error);
  }
}

/**
 * Post a comment on Linear
 */
async function postLinearComment(task: Task, body: string): Promise<void> {
  const apiKey = process.env.LINEAR_API_KEY;
  if (!apiKey || !task.sourceId) return;

  try {
    const client = new LinearClient({ apiKey });
    // Note: for linear_comment tasks, the sourceId might be the comment ID.
    // We ideally need the issue ID here. 
    // If task.metadata.issueId exists, use that.
    const issueId = task.metadata?.issueId || task.sourceId;
    await client.addComment(issueId as string, body);
    logger.info(`[Linear] Posted result to issue ${issueId}`);
  } catch (error) {
    logger.error('[Linear] Error posting comment:', error as Error);
  }
}
