/**
 * CLI Onboard Command
 *
 * Zero-to-running in one command. Detects environment, recommends deployment mode,
 * generates .env, runs setup wizard, starts server.
 *
 * Usage:
 *   profclaw onboard                                    # Interactive
 *   profclaw onboard --non-interactive --mode mini      # CI/Docker
 */

import { Command } from 'commander';
import chalk from 'chalk';
import figlet from 'figlet';
import { select, search, input, Separator } from '@inquirer/prompts';
import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { success, error, info, warn, spinner } from '../utils/output.js';
import type { DeploymentMode } from '../../core/deployment.js';

// Environment Detection

interface EnvironmentInfo {
  os: string;
  arch: string;
  nodeVersion: string;
  totalMemoryMb: number;
  isDocker: boolean;
  hasRedis: boolean;
  hasOllama: boolean;
  hasClaude: boolean;
  hasGit: boolean;
  existingEnv: boolean;
  existingDb: boolean;
}

const DETECT_TIMEOUT_MS = 5000;

/** Wrap a detection check with a timeout so a hung service doesn't block onboarding. */
async function withTimeout<T>(promise: Promise<T>, fallback: T, timeoutMs = DETECT_TIMEOUT_MS): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((resolve) => setTimeout(() => resolve(fallback), timeoutMs)),
  ]);
}

async function detectRedis(): Promise<boolean> {
  try {
    const IORedis = (await import('ioredis')).default;
    const redisUrl = process.env.REDIS_URL || 'redis://localhost:6379';
    const redis = new IORedis(redisUrl, {
      maxRetriesPerRequest: 1,
      connectTimeout: 2000,
      lazyConnect: true,
    });
    await redis.connect();
    await redis.ping();
    await redis.disconnect();
    return true;
  } catch {
    return false;
  }
}

async function detectOllama(): Promise<boolean> {
  try {
    const url = process.env.OLLAMA_BASE_URL || 'http://localhost:11434';
    const res = await fetch(`${url}/api/tags`, { signal: AbortSignal.timeout(2000) });
    return res.ok;
  } catch {
    return false;
  }
}

function detectBinary(name: string): boolean {
  try {
    execSync(`which ${name}`, { stdio: 'ignore', timeout: 3000 });
    return true;
  } catch {
    return false;
  }
}

async function detectEnvironment(): Promise<EnvironmentInfo> {
  const os = await import('node:os');

  const isDocker = existsSync('/.dockerenv') || existsSync('/run/.containerenv');
  const totalMemoryMb = Math.round(os.totalmem() / (1024 * 1024));

  // Run network checks in parallel with timeouts
  const [hasRedis, hasOllama] = await Promise.all([
    withTimeout(detectRedis(), false),
    withTimeout(detectOllama(), false),
  ]);

  // Binary checks are fast, no timeout needed
  const hasClaude = detectBinary('claude');
  const hasGit = detectBinary('git');

  return {
    os: `${os.platform()} ${os.release()}`,
    arch: os.arch(),
    nodeVersion: process.version,
    totalMemoryMb,
    isDocker,
    hasRedis,
    hasOllama,
    hasClaude,
    hasGit,
    existingEnv: existsSync(join(process.cwd(), '.env')),
    existingDb: existsSync(join(process.cwd(), 'data', 'profclaw.db')),
  };
}

function recommendMode(env: EnvironmentInfo): DeploymentMode {
  // Low memory or no Redis: pico
  if (env.totalMemoryMb < 512) return 'pico';

  // Has Redis and plenty of RAM: pro
  if (env.hasRedis && env.totalMemoryMb >= 2048) return 'pro';

  // Default: mini
  return 'mini';
}

// .env Generation

function generateEnvFile(opts: {
  mode: DeploymentMode;
  anthropicKey?: string;
  openaiKey?: string;
  ollamaUrl?: string;
  extraEnvVars?: Record<string, string>;
  port?: string;
}): string {
  const lines: string[] = [
    '# profClaw Configuration',
    `# Generated by: profclaw onboard`,
    `# Date: ${new Date().toISOString()}`,
    '',
    '# Deployment Mode',
    `PROFCLAW_MODE=${opts.mode}`,
    '',
    `PORT=${opts.port || '3000'}`,
    '',
  ];

  if (opts.anthropicKey) {
    lines.push('# AI Provider');
    lines.push(`ANTHROPIC_API_KEY=${opts.anthropicKey}`);
    lines.push('');
  } else if (opts.openaiKey) {
    lines.push('# AI Provider');
    lines.push(`OPENAI_API_KEY=${opts.openaiKey}`);
    lines.push('');
  } else if (opts.ollamaUrl) {
    lines.push('# AI Provider (Ollama - free local AI)');
    lines.push(`OLLAMA_BASE_URL=${opts.ollamaUrl}`);
    lines.push('');
  }

  // Write any extra env vars from selected providers
  if (opts.extraEnvVars) {
    for (const [key, value] of Object.entries(opts.extraEnvVars)) {
      lines.push(`${key}=${value}`);
    }
    if (Object.keys(opts.extraEnvVars).length > 0) lines.push('');
  }

  if (opts.mode === 'pro') {
    lines.push('# Redis (required for pro mode)');
    lines.push('REDIS_URL=redis://localhost:6379');
    lines.push('');
  }

  return lines.join('\n');
}

// Interactive Onboarding

async function runInteractive(): Promise<void> {
  const banner = figlet.textSync('profClaw', { font: 'Standard' });
  console.log(chalk.cyan(banner));
  console.log(chalk.dim('  Onboarding Wizard\n'));

  // Step 1: Detect environment
  console.log(chalk.bold.white('  Step 1: Environment Detection\n'));
  const spin = spinner('Scanning environment...');
  spin.start();
  const env = await detectEnvironment();
  spin.stop();

  // Helpers for display
  const ok = (label: string, value: string) =>
    console.log(`  ${chalk.green('+')} ${chalk.white(label.padEnd(14))} ${value}`);
  const no = (label: string, value: string, hint?: string) => {
    console.log(`  ${chalk.yellow('~')} ${chalk.dim(label.padEnd(14))} ${chalk.dim(value)}`);
    if (hint) console.log(`    ${chalk.dim('\u2514')} ${chalk.yellow(hint)}`);
  };

  const ramGb = (env.totalMemoryMb / 1024).toFixed(0);
  const ramBar = (() => {
    const total = 16; // bar width
    const filled = Math.min(total, Math.round((env.totalMemoryMb / 65536) * total));
    return chalk.green('\u2588'.repeat(filled)) + chalk.dim('\u2591'.repeat(total - filled));
  })();
  const ramWarn = env.totalMemoryMb < 512
    ? chalk.red(' (low - pico mode recommended)')
    : env.totalMemoryMb < 2048
      ? chalk.yellow(' (limited - mini mode recommended)')
      : '';

  // -- System --
  console.log('');
  console.log(`  ${chalk.bold.cyan('System')}`);
  ok('OS', `${env.os} (${env.arch})`);
  ok('Node', env.nodeVersion);
  ok('RAM', `${ramGb} GB ${ramBar}${ramWarn}`);
  if (env.isDocker) {
    ok('Docker', 'Running in container');
  }

  // -- Services --
  console.log('');
  console.log(`  ${chalk.bold.cyan('Services')}`);
  if (env.hasRedis) {
    ok('Redis', chalk.green('connected'));
  } else {
    no('Redis', 'not found (optional)',
      'Install: brew install redis  |  docker run -d -p 6379:6379 redis:alpine');
  }
  if (env.hasOllama) {
    ok('Ollama', chalk.green('running') + ' (free local AI)');
  } else {
    no('Ollama', 'not running (optional)',
      'Install: brew install ollama && ollama serve  |  https://ollama.com/download');
  }

  // -- Tools --
  console.log('');
  console.log(`  ${chalk.bold.cyan('Tools')}`);
  if (env.hasClaude) {
    ok('Claude CLI', 'found');
  } else {
    no('Claude CLI', 'not found (optional)',
      'Install: npm install -g @anthropic-ai/claude-code');
  }
  if (env.hasGit) {
    ok('Git', 'found');
  } else {
    no('Git', 'not found',
      'Install: brew install git  |  https://git-scm.com/downloads');
  }

  // -- Existing Data --
  if (env.existingEnv || env.existingDb) {
    console.log('');
    console.log(`  ${chalk.bold.cyan('Existing Data')}`);
    if (env.existingEnv) ok('.env', 'found');
    if (env.existingDb) ok('Database', 'found');
  }

  const recommended = recommendMode(env);
  console.log('');
  console.log(`  ${chalk.cyan('Recommended mode:')} ${chalk.bold(recommended)}`);

  // Step 2: Choose mode (arrow keys)
  console.log(chalk.bold.white('\n  Step 2: Deployment Mode\n'));

  let mode: DeploymentMode;
  try {
    mode = await select<DeploymentMode>({
      message: 'Select deployment mode',
      default: recommended,
      choices: [
        {
          name: `Pico  - Agent + tools only, ~50MB RAM${recommended === 'pico' ? chalk.green(' (recommended)') : ''}`,
          value: 'pico' as const,
          description: 'Minimal footprint. CLI agent, tool execution, no web UI.',
        },
        {
          name: `Mini  - Dashboard, cron, integrations, ~150MB RAM${recommended === 'mini' ? chalk.green(' (recommended)') : ''}`,
          value: 'mini' as const,
          description: 'Web dashboard, scheduled jobs, GitHub/Jira/Linear webhooks.',
        },
        {
          name: `Pro   - Everything, Redis required, ~300MB RAM${recommended === 'pro' ? chalk.green(' (recommended)') : ''}`,
          value: 'pro' as const,
          description: 'BullMQ queues, plugins, sync engine, multi-agent orchestration.',
        },
      ],
      theme: { prefix: '  ', style: { highlight: (text: string) => chalk.cyan.bold(text) } },
    });
  } catch {
    console.log(chalk.dim('\n  Cancelled.'));
    process.exit(0);
  }
  success(`Mode: ${mode}`);

  // Step 3: AI Provider (searchable list)
  console.log(chalk.bold.white('\n  Step 3: AI Provider\n'));
  let anthropicKey: string | undefined;
  let openaiKey: string | undefined;
  let ollamaUrl: string | undefined;

  const hasExistingProvider = !!process.env.ANTHROPIC_API_KEY || !!process.env.OPENAI_API_KEY;
  if (hasExistingProvider) {
    const which = process.env.ANTHROPIC_API_KEY ? 'Anthropic' : 'OpenAI';
    info(`AI provider already configured from environment (${which}).`);
  } else {
    // Provider catalog
    const providers = [
      { key: 'anthropic', name: 'Anthropic', models: 'Claude 4.x, 3.5 Sonnet', envVar: 'ANTHROPIC_API_KEY', category: 'Popular', tag: 'recommended' },
      { key: 'openai', name: 'OpenAI', models: 'GPT-4o, o1, o3', envVar: 'OPENAI_API_KEY', category: 'Popular', tag: '' },
      { key: 'google', name: 'Google AI', models: 'Gemini 2.x, Flash', envVar: 'GOOGLE_GENERATIVE_AI_API_KEY', category: 'Popular', tag: '' },
      { key: 'ollama', name: 'Ollama', models: 'Llama, Mistral, Qwen', envVar: 'OLLAMA_BASE_URL', category: 'Popular', tag: env.hasOllama ? 'detected' : 'free, local' },
      { key: 'groq', name: 'Groq', models: 'Llama, Mixtral', envVar: 'GROQ_API_KEY', category: 'Fast Inference', tag: 'fast' },
      { key: 'cerebras', name: 'Cerebras', models: 'Llama 3.3 70B', envVar: 'CEREBRAS_API_KEY', category: 'Fast Inference', tag: 'fast' },
      { key: 'fireworks', name: 'Fireworks', models: 'Llama, Mixtral', envVar: 'FIREWORKS_API_KEY', category: 'Fast Inference', tag: '' },
      { key: 'together', name: 'Together', models: 'Open models', envVar: 'TOGETHER_API_KEY', category: 'Fast Inference', tag: '' },
      { key: 'azure', name: 'Azure OpenAI', models: 'GPT-4o', envVar: 'AZURE_OPENAI_API_KEY', category: 'Enterprise', tag: 'enterprise' },
      { key: 'bedrock', name: 'AWS Bedrock', models: 'Claude, Titan, Llama', envVar: 'AWS_ACCESS_KEY_ID', category: 'Enterprise', tag: 'enterprise' },
      { key: 'watsonx', name: 'IBM Watsonx', models: 'Granite, Llama', envVar: 'WATSONX_API_KEY', category: 'Enterprise', tag: 'enterprise' },
      { key: 'deepseek', name: 'DeepSeek', models: 'V3, R1 (reasoning)', envVar: 'DEEPSEEK_API_KEY', category: 'More Providers', tag: '' },
      { key: 'mistral', name: 'Mistral', models: 'Large, Codestral', envVar: 'MISTRAL_API_KEY', category: 'More Providers', tag: '' },
      { key: 'xai', name: 'xAI', models: 'Grok', envVar: 'XAI_API_KEY', category: 'More Providers', tag: '' },
      { key: 'perplexity', name: 'Perplexity', models: 'Sonar (search)', envVar: 'PERPLEXITY_API_KEY', category: 'More Providers', tag: 'search' },
      { key: 'cohere', name: 'Cohere', models: 'Command R+', envVar: 'COHERE_API_KEY', category: 'More Providers', tag: '' },
      { key: 'openrouter', name: 'OpenRouter', models: 'Any model (proxy)', envVar: 'OPENROUTER_API_KEY', category: 'Aggregators', tag: 'multi-model' },
      { key: 'replicate', name: 'Replicate', models: 'Open-source models', envVar: 'REPLICATE_API_TOKEN', category: 'Aggregators', tag: '' },
      { key: 'github-models', name: 'GitHub Models', models: 'Azure-backed', envVar: 'GITHUB_TOKEN', category: 'Aggregators', tag: '' },
      { key: 'huggingface', name: 'HuggingFace', models: 'Inference API', envVar: 'HF_TOKEN', category: 'Aggregators', tag: '' },
      { key: 'nvidia-nim', name: 'NVIDIA NIM', models: 'Llama, Nemotron', envVar: 'NVIDIA_NIM_API_KEY', category: 'Aggregators', tag: '' },
      { key: 'zhipu', name: 'Zhipu AI', models: 'GLM-4, GLM-5', envVar: 'ZHIPU_API_KEY', category: 'Asia', tag: '' },
      { key: 'moonshot', name: 'Moonshot', models: 'Kimi (128K context)', envVar: 'MOONSHOT_API_KEY', category: 'Asia', tag: '' },
      { key: 'qwen', name: 'Qwen', models: 'Qwen Max, Plus', envVar: 'QWEN_API_KEY', category: 'Asia', tag: '' },
      { key: 'minimax', name: 'MiniMax', models: 'abab series', envVar: 'MINIMAX_API_KEY', category: 'Asia', tag: '' },
      { key: 'volcengine', name: 'Volcengine', models: 'Doubao (Bytedance)', envVar: 'VOLCENGINE_API_KEY', category: 'Asia', tag: '' },
      { key: 'qianfan', name: 'Qianfan', models: 'ERNIE (Baidu)', envVar: 'QIANFAN_API_KEY', category: 'Asia', tag: '' },
    ];

    // Check which providers have keys in env
    const detected = new Set<string>();
    for (const p of providers) {
      if (process.env[p.envVar]) detected.add(p.key);
    }
    if (env.hasOllama) detected.add('ollama');

    // Build searchable choices grouped by category
    let chosenProvider: string;

    try {
      chosenProvider = await search<string>({
        message: 'Select AI provider (type to filter, arrows to navigate)',
        source: (term: string | undefined) => {
          const results: Array<Separator | { name: string; value: string; description: string; short: string }> = [];
          const filter = (term || '').toLowerCase();
          let lastCategory = '';

          for (const p of providers) {
            // Filter by name, key, models, category, or tag
            if (filter && ![p.name, p.key, p.models, p.category, p.tag]
              .some(s => s.toLowerCase().includes(filter))) {
              continue;
            }

            // Add category separator
            if (p.category !== lastCategory) {
              if (results.length > 0) results.push(new Separator());
              results.push(new Separator(chalk.bold.cyan(` ${p.category} `)));
              lastCategory = p.category;
            }

            const det = detected.has(p.key) ? chalk.green(' *') : '';
            const tag = p.tag ? ` ${chalk.dim(`[${p.tag}]`)}` : '';
            results.push({
              name: `${p.name.padEnd(16)} ${chalk.dim(p.models)}${tag}${det}`,
              value: p.key,
              description: `${p.envVar}`,
              short: p.name,
            });
          }

          // Always add skip option at the end
          if (!filter || 'skip'.includes(filter)) {
            results.push(new Separator());
            results.push({
              name: chalk.dim('Skip for now'),
              value: 'skip',
              description: 'Configure later with: profclaw provider',
              short: 'Skip',
            });
          }

          return results;
        },
        theme: { prefix: '  ', style: { highlight: (text: string) => chalk.cyan.bold(text) } },
      });
    } catch {
      console.log(chalk.dim('\n  Cancelled.'));
      process.exit(0);
    }

    if (chosenProvider !== 'skip') {
      const chosen = providers.find(p => p.key === chosenProvider)!;
      console.log(`\n  ${chalk.bold(chosen.name)} selected`);
      console.log(chalk.dim(`  Env var: ${chosen.envVar}`));

      if (chosen.key === 'ollama') {
        if (env.hasOllama) {
          ollamaUrl = process.env.OLLAMA_BASE_URL || 'http://localhost:11434';
        } else {
          try {
            ollamaUrl = await input({
              message: 'Ollama URL',
              default: 'http://localhost:11434',
              theme: { prefix: '  ' },
            });
          } catch {
            ollamaUrl = 'http://localhost:11434';
          }
        }
        success(`Ollama: ${ollamaUrl}`);
      } else if (detected.has(chosen.key)) {
        success(`${chosen.name} already configured from ${chosen.envVar}`);
      } else {
        try {
          const keyInput = await input({
            message: chosen.envVar,
            theme: { prefix: '  ' },
          });
          if (keyInput) {
            if (chosen.key === 'anthropic') anthropicKey = keyInput;
            else if (chosen.key === 'openai') openaiKey = keyInput;
            else {
              process.env[chosen.envVar] = keyInput;
            }
            success(`${chosen.name} configured.`);
          } else {
            warn('No key provided, skipping.');
          }
        } catch {
          warn('Input cancelled, skipping provider.');
        }
      }
    } else {
      info('AI provider skipped. Configure later: profclaw provider');
    }
  }

  // Step 4: Generate .env
  console.log(chalk.bold.white('\n  Step 4: Configuration\n'));

  if (!env.existingEnv) {
    const envContent = generateEnvFile({
      mode,
      anthropicKey,
      openaiKey,
      ollamaUrl,
    });
    const envPath = join(process.cwd(), '.env');
    try {
      writeFileSync(envPath, envContent, { mode: 0o600 });
      success('.env file created.');
    } catch (err) {
      error(`Failed to write .env: ${err instanceof Error ? err.message : 'unknown'}`);
      info('Create .env manually with the values above.');
    }
  } else {
    info('.env file already exists. Updating PROFCLAW_MODE...');
    const envPath = join(process.cwd(), '.env');
    let content = readFileSync(envPath, 'utf-8');
    if (content.includes('PROFCLAW_MODE=')) {
      content = content.replace(/PROFCLAW_MODE=\w+/, `PROFCLAW_MODE=${mode}`);
    } else {
      content += `\nPROFCLAW_MODE=${mode}\n`;
    }
    writeFileSync(envPath, content);
    success(`PROFCLAW_MODE=${mode} set in .env`);
  }

  // Step 5: Run setup wizard
  console.log(chalk.bold.white('\n  Step 5: Setup\n'));
  info('Launching setup wizard for admin account and provider configuration...\n');

  try {
    const { setupCommand } = await import('./setup.js');
    const setupCmd = setupCommand();
    await setupCmd.parseAsync(['node', 'setup']);
  } catch (err) {
    error(`Setup wizard failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    info('You can run it again later: profclaw setup');
    return;
  }

  // Step 6: Post-setup validation
  console.log(chalk.bold.white('\n  Step 6: Validation\n'));
  const postSpin = spinner('Validating installation...');
  postSpin.start();

  const checks: Array<{ label: string; ok: boolean }> = [];

  // Check .env exists
  const envExists = existsSync(join(process.cwd(), '.env'));
  checks.push({ label: '.env file', ok: envExists });

  // Check config exists
  const configExists = existsSync(join(process.cwd(), 'config', 'settings.yml'));
  checks.push({ label: 'config/settings.yml', ok: configExists });

  // Check database was created
  const dbExists = existsSync(join(process.cwd(), 'data', 'profclaw.db'));
  checks.push({ label: 'Database', ok: dbExists });

  postSpin.stop();

  for (const check of checks) {
    const icon = check.ok ? chalk.green('  +') : chalk.red('  -');
    console.log(`${icon} ${check.label}: ${check.ok ? 'OK' : 'missing'}`);
  }

  const allPassed = checks.every((c) => c.ok);
  if (allPassed) {
    console.log('');
    success('Onboarding complete! Start the server:');
    console.log(`\n  ${chalk.cyan.bold('profclaw serve')}\n`);
  } else {
    console.log('');
    warn('Some checks did not pass. You may need to run setup again:');
    console.log(`\n  ${chalk.cyan('profclaw setup')}\n`);
  }
}

// Non-Interactive Onboarding

async function runNonInteractive(options: {
  mode?: string;
  provider?: string;
  port?: string;
}): Promise<void> {
  console.log(chalk.dim('  Running onboard in non-interactive mode...\n'));

  const spin = spinner('Detecting environment...');
  spin.start();
  const env = await detectEnvironment();
  spin.stop();

  const mode = (options.mode || recommendMode(env)) as DeploymentMode;
  success(`Mode: ${mode}`);

  // Generate .env if it doesn't exist
  if (!env.existingEnv) {
    try {
      const envPath = join(process.cwd(), '.env');
      const envContent = generateEnvFile({ mode, port: options.port });
      writeFileSync(envPath, envContent, { mode: 0o600 }); // Restrict permissions
      success('.env created');
    } catch (err) {
      error(`Failed to write .env: ${err instanceof Error ? err.message : 'permission denied'}`);
      info('Create .env manually with PROFCLAW_MODE=' + mode);
    }
  }

  // Delegate to setup --non-interactive
  try {
    const { setupCommand } = await import('./setup.js');
    const setupCmd = setupCommand();
    const args = ['node', 'setup', '--non-interactive'];
    if (options.provider) args.push('--ai-provider', options.provider);
    await setupCmd.parseAsync(args);
  } catch (err) {
    error(`Setup failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    info('Run setup manually: profclaw setup');
  }

  success('Non-interactive onboarding complete.');
}

// Command Registration

export function onboardCommand(): Command {
  const cmd = new Command('onboard')
    .description('Zero-to-running onboarding wizard (environment detection + setup + start)')
    .option('--non-interactive', 'Run without prompts')
    .option('--mode <mode>', 'Deployment mode: pico, mini, pro')
    .option('--provider <provider>', 'AI provider: anthropic, openai, ollama')
    .option('--port <port>', 'Server port (default: 3000)')
    .action(async (options) => {
      try {
        if (options.nonInteractive) {
          await runNonInteractive({
            mode: options.mode,
            provider: options.provider,
            port: options.port,
          });
        } else {
          await runInteractive();
        }
      } catch (err) {
        error(err instanceof Error ? err.message : 'Onboarding failed');
        process.exit(1);
      }
    });

  return cmd;
}
