/**
 * CLI Onboard Command
 *
 * Zero-to-running in one command. Detects environment, recommends deployment mode,
 * generates .env, runs setup wizard, starts server.
 *
 * Usage:
 *   profclaw onboard                                    # Interactive
 *   profclaw onboard --non-interactive --mode mini      # CI/Docker
 */

import { Command } from 'commander';
import chalk from 'chalk';
import figlet from 'figlet';
import { createInterface } from 'readline/promises';
import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';
import { success, error, info, warn, spinner } from '../utils/output.js';
import type { DeploymentMode } from '../../core/deployment.js';

// ---------------------------------------------------------------------------
// Environment Detection
// ---------------------------------------------------------------------------

interface EnvironmentInfo {
  os: string;
  arch: string;
  nodeVersion: string;
  totalMemoryMb: number;
  isDocker: boolean;
  hasRedis: boolean;
  hasOllama: boolean;
  hasClaude: boolean;
  hasGit: boolean;
  existingEnv: boolean;
  existingDb: boolean;
}

const DETECT_TIMEOUT_MS = 5000;

/** Wrap a detection check with a timeout so a hung service doesn't block onboarding. */
async function withTimeout<T>(promise: Promise<T>, fallback: T, timeoutMs = DETECT_TIMEOUT_MS): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((resolve) => setTimeout(() => resolve(fallback), timeoutMs)),
  ]);
}

async function detectRedis(): Promise<boolean> {
  try {
    const IORedis = (await import('ioredis')).default;
    const redisUrl = process.env.REDIS_URL || 'redis://localhost:6379';
    const redis = new IORedis(redisUrl, {
      maxRetriesPerRequest: 1,
      connectTimeout: 2000,
      lazyConnect: true,
    });
    await redis.connect();
    await redis.ping();
    await redis.disconnect();
    return true;
  } catch {
    return false;
  }
}

async function detectOllama(): Promise<boolean> {
  try {
    const url = process.env.OLLAMA_BASE_URL || 'http://localhost:11434';
    const res = await fetch(`${url}/api/tags`, { signal: AbortSignal.timeout(2000) });
    return res.ok;
  } catch {
    return false;
  }
}

function detectBinary(name: string): boolean {
  try {
    execSync(`which ${name}`, { stdio: 'ignore', timeout: 3000 });
    return true;
  } catch {
    return false;
  }
}

async function detectEnvironment(): Promise<EnvironmentInfo> {
  const os = await import('node:os');

  const isDocker = existsSync('/.dockerenv') || existsSync('/run/.containerenv');
  const totalMemoryMb = Math.round(os.totalmem() / (1024 * 1024));

  // Run network checks in parallel with timeouts
  const [hasRedis, hasOllama] = await Promise.all([
    withTimeout(detectRedis(), false),
    withTimeout(detectOllama(), false),
  ]);

  // Binary checks are fast, no timeout needed
  const hasClaude = detectBinary('claude');
  const hasGit = detectBinary('git');

  return {
    os: `${os.platform()} ${os.release()}`,
    arch: os.arch(),
    nodeVersion: process.version,
    totalMemoryMb,
    isDocker,
    hasRedis,
    hasOllama,
    hasClaude,
    hasGit,
    existingEnv: existsSync(join(process.cwd(), '.env')),
    existingDb: existsSync(join(process.cwd(), 'data', 'profclaw.db')),
  };
}

function recommendMode(env: EnvironmentInfo): DeploymentMode {
  // Low memory or no Redis: pico
  if (env.totalMemoryMb < 512) return 'pico';

  // Has Redis and plenty of RAM: pro
  if (env.hasRedis && env.totalMemoryMb >= 2048) return 'pro';

  // Default: mini
  return 'mini';
}

// ---------------------------------------------------------------------------
// .env Generation
// ---------------------------------------------------------------------------

function generateEnvFile(opts: {
  mode: DeploymentMode;
  anthropicKey?: string;
  openaiKey?: string;
  ollamaUrl?: string;
  port?: string;
}): string {
  const lines: string[] = [
    '# profClaw Configuration',
    `# Generated by: profclaw onboard`,
    `# Date: ${new Date().toISOString()}`,
    '',
    '# Deployment Mode',
    `PROFCLAW_MODE=${opts.mode}`,
    '',
    `PORT=${opts.port || '3000'}`,
    '',
  ];

  if (opts.anthropicKey) {
    lines.push('# AI Provider');
    lines.push(`ANTHROPIC_API_KEY=${opts.anthropicKey}`);
    lines.push('');
  } else if (opts.openaiKey) {
    lines.push('# AI Provider');
    lines.push(`OPENAI_API_KEY=${opts.openaiKey}`);
    lines.push('');
  } else if (opts.ollamaUrl) {
    lines.push('# AI Provider (Ollama - free local AI)');
    lines.push(`OLLAMA_BASE_URL=${opts.ollamaUrl}`);
    lines.push('');
  }

  if (opts.mode === 'pro') {
    lines.push('# Redis (required for pro mode)');
    lines.push('REDIS_URL=redis://localhost:6379');
    lines.push('');
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Interactive Onboarding
// ---------------------------------------------------------------------------

async function prompt(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  const answer = await rl.question(chalk.bold(question));
  return answer.trim();
}

async function promptChoice(
  rl: ReturnType<typeof createInterface>,
  question: string,
  options: { key: string; label: string }[],
): Promise<string> {
  console.log('');
  console.log(chalk.bold(question));
  for (const opt of options) {
    console.log(`  ${chalk.cyan(opt.key)}) ${opt.label}`);
  }
  const validKeys = options.map(o => o.key);
  while (true) {
    const answer = await prompt(rl, `Choice [${validKeys.join('/')}]: `);
    if (validKeys.includes(answer)) return answer;
    console.log(chalk.red(`  Invalid choice. Options: ${validKeys.join(', ')}`));
  }
}

async function runInteractive(): Promise<void> {
  const banner = figlet.textSync('profClaw', { font: 'Standard' });
  console.log(chalk.cyan(banner));
  console.log(chalk.dim('  Onboarding Wizard\n'));

  // Step 1: Detect environment
  console.log(chalk.bold.white('  Step 1: Environment Detection\n'));
  const spin = spinner('Scanning environment...');
  spin.start();
  const env = await detectEnvironment();
  spin.stop();

  const mark = (ok: boolean) => (ok ? chalk.green('  +') : chalk.dim('  -'));
  console.log(`${mark(true)} OS: ${env.os} (${env.arch})`);
  console.log(`${mark(true)} Node: ${env.nodeVersion}`);
  console.log(`${mark(true)} RAM: ${env.totalMemoryMb} MB`);
  console.log(`${mark(env.isDocker)} Docker: ${env.isDocker ? 'yes' : 'no'}`);
  console.log(`${mark(env.hasRedis)} Redis: ${env.hasRedis ? 'connected' : 'not found'}`);
  console.log(`${mark(env.hasOllama)} Ollama: ${env.hasOllama ? 'running' : 'not found'}`);
  console.log(`${mark(env.hasClaude)} Claude CLI: ${env.hasClaude ? 'found' : 'not found'}`);
  console.log(`${mark(env.hasGit)} Git: ${env.hasGit ? 'found' : 'not found'}`);

  const recommended = recommendMode(env);
  console.log(`\n  ${chalk.cyan('Recommended mode:')} ${chalk.bold(recommended)}`);

  const rl = createInterface({ input: process.stdin, output: process.stdout });

  // Step 2: Choose mode
  console.log(chalk.bold.white('\n  Step 2: Deployment Mode\n'));
  const modeChoice = await promptChoice(rl, '  Select deployment mode:', [
    { key: '1', label: `Pico -- Agent + tools only, ~50MB RAM${recommended === 'pico' ? chalk.green(' (recommended)') : ''}` },
    { key: '2', label: `Mini -- + Dashboard, cron, integrations, ~150MB RAM${recommended === 'mini' ? chalk.green(' (recommended)') : ''}` },
    { key: '3', label: `Pro -- Everything, Redis required, ~300MB RAM${recommended === 'pro' ? chalk.green(' (recommended)') : ''}` },
  ]);
  const mode: DeploymentMode = modeChoice === '1' ? 'pico' : modeChoice === '2' ? 'mini' : 'pro';
  success(`Mode: ${mode}`);

  // Step 3: AI Provider
  console.log(chalk.bold.white('\n  Step 3: AI Provider\n'));
  let anthropicKey: string | undefined;
  let openaiKey: string | undefined;
  let ollamaUrl: string | undefined;

  const hasExistingProvider = !!process.env.ANTHROPIC_API_KEY || !!process.env.OPENAI_API_KEY;
  if (hasExistingProvider) {
    info('AI provider already configured from environment.');
  } else {
    const providerChoice = await promptChoice(rl, '  Select AI provider:', [
      { key: '1', label: 'Anthropic (Claude) -- recommended' },
      { key: '2', label: 'OpenAI (GPT-4o)' },
      { key: '3', label: `Ollama (free, local)${env.hasOllama ? chalk.green(' -- detected!') : ''}` },
      { key: '4', label: 'Skip for now' },
    ]);

    if (providerChoice === '1') {
      anthropicKey = await prompt(rl, '  Anthropic API Key: ');
      if (anthropicKey) success('Anthropic key saved.');
    } else if (providerChoice === '2') {
      openaiKey = await prompt(rl, '  OpenAI API Key: ');
      if (openaiKey) success('OpenAI key saved.');
    } else if (providerChoice === '3') {
      ollamaUrl = env.hasOllama
        ? (process.env.OLLAMA_BASE_URL || 'http://localhost:11434')
        : await prompt(rl, '  Ollama URL [http://localhost:11434]: ') || 'http://localhost:11434';
      success(`Ollama: ${ollamaUrl}`);
    }
  }

  // Step 4: Generate .env
  console.log(chalk.bold.white('\n  Step 4: Configuration\n'));

  if (!env.existingEnv) {
    const envContent = generateEnvFile({
      mode,
      anthropicKey,
      openaiKey,
      ollamaUrl,
    });
    const envPath = join(process.cwd(), '.env');
    try {
      writeFileSync(envPath, envContent, { mode: 0o600 });
      success('.env file created.');
    } catch (err) {
      error(`Failed to write .env: ${err instanceof Error ? err.message : 'unknown'}`);
      info('Create .env manually with the values above.');
    }
  } else {
    info('.env file already exists. Updating PROFCLAW_MODE...');
    const envPath = join(process.cwd(), '.env');
    let content = readFileSync(envPath, 'utf-8');
    if (content.includes('PROFCLAW_MODE=')) {
      content = content.replace(/PROFCLAW_MODE=\w+/, `PROFCLAW_MODE=${mode}`);
    } else {
      content += `\nPROFCLAW_MODE=${mode}\n`;
    }
    writeFileSync(envPath, content);
    success(`PROFCLAW_MODE=${mode} set in .env`);
  }

  rl.close();

  // Step 5: Run setup wizard
  console.log(chalk.bold.white('\n  Step 5: Setup\n'));
  info('Launching setup wizard for admin account and provider configuration...\n');

  try {
    const { setupCommand } = await import('./setup.js');
    const setupCmd = setupCommand();
    await setupCmd.parseAsync(['node', 'profclaw', 'setup']);
  } catch (err) {
    error(`Setup wizard failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    info('You can run it again later: profclaw setup');
    return;
  }

  // Step 6: Post-setup validation
  console.log(chalk.bold.white('\n  Step 6: Validation\n'));
  const postSpin = spinner('Validating installation...');
  postSpin.start();

  const checks: Array<{ label: string; ok: boolean }> = [];

  // Check .env exists
  const envExists = existsSync(join(process.cwd(), '.env'));
  checks.push({ label: '.env file', ok: envExists });

  // Check config exists
  const configExists = existsSync(join(process.cwd(), 'config', 'settings.yml'));
  checks.push({ label: 'config/settings.yml', ok: configExists });

  // Check database was created
  const dbExists = existsSync(join(process.cwd(), 'data', 'profclaw.db'));
  checks.push({ label: 'Database', ok: dbExists });

  postSpin.stop();

  for (const check of checks) {
    const icon = check.ok ? chalk.green('  +') : chalk.red('  -');
    console.log(`${icon} ${check.label}: ${check.ok ? 'OK' : 'missing'}`);
  }

  const allPassed = checks.every((c) => c.ok);
  if (allPassed) {
    console.log('');
    success('Onboarding complete! Start the server:');
    console.log(`\n  ${chalk.cyan.bold('profclaw serve')}\n`);
  } else {
    console.log('');
    warn('Some checks did not pass. You may need to run setup again:');
    console.log(`\n  ${chalk.cyan('profclaw setup')}\n`);
  }
}

// ---------------------------------------------------------------------------
// Non-Interactive Onboarding
// ---------------------------------------------------------------------------

async function runNonInteractive(options: {
  mode?: string;
  provider?: string;
  port?: string;
}): Promise<void> {
  console.log(chalk.dim('  Running onboard in non-interactive mode...\n'));

  const spin = spinner('Detecting environment...');
  spin.start();
  const env = await detectEnvironment();
  spin.stop();

  const mode = (options.mode || recommendMode(env)) as DeploymentMode;
  success(`Mode: ${mode}`);

  // Generate .env if it doesn't exist
  if (!env.existingEnv) {
    try {
      const envPath = join(process.cwd(), '.env');
      const envContent = generateEnvFile({ mode, port: options.port });
      writeFileSync(envPath, envContent, { mode: 0o600 }); // Restrict permissions
      success('.env created');
    } catch (err) {
      error(`Failed to write .env: ${err instanceof Error ? err.message : 'permission denied'}`);
      info('Create .env manually with PROFCLAW_MODE=' + mode);
    }
  }

  // Delegate to setup --non-interactive
  try {
    const { setupCommand } = await import('./setup.js');
    const setupCmd = setupCommand();
    const args = ['node', 'profclaw', 'setup', '--non-interactive'];
    if (options.provider) args.push('--ai-provider', options.provider);
    await setupCmd.parseAsync(args);
  } catch (err) {
    error(`Setup failed: ${err instanceof Error ? err.message : 'Unknown error'}`);
    info('Run setup manually: profclaw setup');
  }

  success('Non-interactive onboarding complete.');
}

// ---------------------------------------------------------------------------
// Command Registration
// ---------------------------------------------------------------------------

export function onboardCommand(): Command {
  const cmd = new Command('onboard')
    .description('Zero-to-running onboarding wizard (environment detection + setup + start)')
    .option('--non-interactive', 'Run without prompts')
    .option('--mode <mode>', 'Deployment mode: pico, mini, pro')
    .option('--provider <provider>', 'AI provider: anthropic, openai, ollama')
    .option('--port <port>', 'Server port (default: 3000)')
    .action(async (options) => {
      try {
        if (options.nonInteractive) {
          await runNonInteractive({
            mode: options.mode,
            provider: options.provider,
            port: options.port,
          });
        } else {
          await runInteractive();
        }
      } catch (err) {
        error(err instanceof Error ? err.message : 'Onboarding failed');
        process.exit(1);
      }
    });

  return cmd;
}
